<?php

namespace Darkink\AuthorizationServerUI\View\Components\Shared;

return [
    Button::class,
    Link::class,
    Icon::class,
    Select::class,
    ManySelector::class,
    EditableList::class,
    InputGroup::class,
    InputBase::class,
    InputTextarea::class,
    InnerFormLayout::class,
    OuterFormLayout::class,
    ActionsFormLayout::class,
    DefaultHeader::class,
    InnerModalLayout::class,
    OuterModalLayout::class,
    DefaultModalIcon::class,
    DefaultModalTitle::class,
    DefaultModalContent::class,
    DefaultModalActions::class,
    OuterListLayout::class,
    DefaultListActions::class,
    DefaultTableHeaderColumn::class,
    TableSortHeader::class,
    DefaultTableRow::class,
    DefaultTableRowContent::class,
    DefaultTableRowActions::class,
    Dropdown::class,
    DropdownLink::class,
    ValidationErrorHelper::class,
    Listbox::class,
    ManageList::class,
    Progress::class,
    Tab::class,
    TabItem::class,
    EntityList::class,
    DatePicker::class
];
